local M = {}

M.ui_bg = "#080808"
M.status_bg = M.ui_bg
M.pane_border = "#2a2a2a"

require("catppuccin").setup({
	flavour = "frappe",
	color_overrides = {
		frappe = {
			base = M.ui_bg,
			mantle = M.ui_bg,
			crust = M.ui_bg,
		},
	},
	custom_highlights = function(colors)
		return {
			Normal = { bg = M.ui_bg },
			NormalNC = { bg = M.ui_bg },
			SignColumn = { bg = M.ui_bg },
			EndOfBuffer = { bg = M.ui_bg },
			PiPaneBorder = { fg = M.pane_border, bg = M.ui_bg },
			PiStatusFooter = { bg = M.status_bg },
			PiStatusFooterNormal = { fg = colors.text, bg = M.status_bg },
			PiInputTitle = { fg = colors.subtext1, bg = M.ui_bg },
			PiOverviewStatusLine = { fg = colors.subtext1, bg = M.ui_bg },
			PiOverviewTitle = { fg = colors.text, bg = M.ui_bg, bold = true },
			PiOverviewNewSession = { fg = colors.text, bg = M.ui_bg, italic = true },
			PiOverviewDetailTitle = { fg = colors.red, bg = M.ui_bg, bold = true },
			PiOverviewValue = { fg = colors.green, bg = M.ui_bg },
			PiApprovalKey = { fg = colors.text, bg = M.ui_bg },
			PiApprovalValue = { fg = colors.green, bg = M.ui_bg },
			PiInputSidebarFull = { fg = colors.green, bg = M.ui_bg },
			PiInputSidebarEdit = { fg = colors.blue, bg = M.ui_bg },
			PiInputSidebarAsk = { fg = colors.peach, bg = M.ui_bg },
			PiInputSidebarReadonly = { fg = colors.red, bg = M.ui_bg },
			PiInputSidebarUnknown = { fg = colors.overlay0, bg = M.ui_bg },
			PiUsageStats = { fg = colors.subtext1, bg = M.status_bg },
			PiUsageInput = { fg = colors.blue, bg = M.status_bg },
			PiUsageOutput = { fg = colors.red, bg = M.status_bg },
			PiUsageContext = { fg = colors.overlay1, bg = M.status_bg },
			PiUsageCost = { fg = colors.green, bg = M.status_bg },
			PiUserHeader = { fg = colors.blue, bg = "#102033", bold = true },
			PiAssistantHeader = { fg = colors.mauve, bg = "#1b1424", bold = true },
			PiTreeUser = { fg = colors.blue, bg = M.ui_bg, bold = true },
			PiTreeAssistant = { fg = colors.mauve, bg = M.ui_bg, bold = true },
			PiTreeTool = { fg = colors.peach, bg = M.ui_bg, bold = true },
			PiTreeCustom = { fg = colors.teal, bg = M.ui_bg, bold = true },
			PiTreeMeta = { fg = colors.subtext1, bg = M.ui_bg, bold = true },
			PiTreeWorkspace1 = { fg = colors.rosewater, bg = M.ui_bg, bold = true },
			PiTreeWorkspace2 = { fg = colors.flamingo, bg = M.ui_bg, bold = true },
			PiTreeWorkspace3 = { fg = colors.pink, bg = M.ui_bg, bold = true },
			PiTreeWorkspace4 = { fg = colors.mauve, bg = M.ui_bg, bold = true },
			PiTreeWorkspace5 = { fg = colors.red, bg = M.ui_bg, bold = true },
			PiTreeWorkspace6 = { fg = colors.maroon, bg = M.ui_bg, bold = true },
			PiTreeWorkspace7 = { fg = colors.peach, bg = M.ui_bg, bold = true },
			PiTreeWorkspace8 = { fg = colors.yellow, bg = M.ui_bg, bold = true },
			PiTreeWorkspace9 = { fg = colors.green, bg = M.ui_bg, bold = true },
			PiTreeWorkspace10 = { fg = colors.teal, bg = M.ui_bg, bold = true },
			PiTreeWorkspace11 = { fg = colors.sky, bg = M.ui_bg, bold = true },
			PiTreeWorkspace12 = { fg = colors.sapphire, bg = M.ui_bg, bold = true },
			PiTreeWorkspace13 = { fg = colors.blue, bg = M.ui_bg, bold = true },
			PiTreeWorkspace14 = { fg = colors.lavender, bg = M.ui_bg, bold = true },
			PiQuoteBar = { fg = colors.pink, bg = M.ui_bg },
			PiToolQuote = { fg = colors.overlay1, bg = M.ui_bg },
			PiTodoQuote = { fg = colors.subtext0, bg = "#141414", bold = true },
			PiToolEditQuote = { fg = colors.peach, bg = M.ui_bg, bold = true },
			PiToolWorkspaceQuote = { fg = colors.teal, bg = M.ui_bg, bold = true },
			PiEditAdd = { fg = colors.green, bg = M.ui_bg, bold = false },
			PiEditDelete = { fg = colors.red, bg = M.ui_bg, bold = false },
			PiEditBlockCount = { fg = colors.overlay1, bg = M.ui_bg, bold = false },
			PiSubagentQuote = { fg = colors.lavender, bg = "#18182d", bold = true },
			PiThinkingQuote = { fg = colors.sky, bg = M.ui_bg, bold = true },
			PiSkillQuote = { fg = colors.green, bg = "#102418", bold = true },
			PiModeFull = { fg = colors.green, bg = M.status_bg, bold = true },
			PiModeEdit = { fg = colors.blue, bg = M.status_bg, bold = true },
			PiModeAsk = { fg = colors.peach, bg = M.status_bg, bold = true },
			PiModeReadonly = { fg = colors.red, bg = M.status_bg, bold = true },
			PiModeUnknown = { fg = colors.subtext1, bg = M.status_bg, bold = true },
			PiIntegrationAsk = { fg = colors.yellow, bg = M.status_bg, bold = true },
			PiIntegrationAllowed = { fg = colors.green, bg = M.status_bg, bold = true },
			PiWorkspaceLocal = { fg = colors.overlay0, bg = M.status_bg },
			PiWorkspaceActive = { fg = colors.teal, bg = M.status_bg, bold = true },
			PiNotifyOn = { fg = colors.green, bg = M.status_bg, bold = true },
			PiNotifyOff = { fg = colors.overlay0, bg = M.status_bg },
			PiThinkingOff = { fg = colors.overlay0, bg = M.status_bg },
			PiThinkingMinimal = { fg = colors.sky, bg = M.status_bg, bold = true },
			PiThinkingLow = { fg = colors.green, bg = M.status_bg, bold = true },
			PiThinkingMedium = { fg = colors.yellow, bg = M.status_bg, bold = true },
			PiThinkingHigh = { fg = colors.peach, bg = M.status_bg, bold = true },
			PiThinkingXhigh = { fg = colors.red, bg = M.status_bg, bold = true },
			PiActivity = { fg = colors.mauve, bg = M.status_bg, bold = true },
			StatusLine = { fg = M.pane_border, bg = M.ui_bg },
			StatusLineNC = { fg = M.pane_border, bg = M.ui_bg },
			MsgArea = { fg = colors.text, bg = M.status_bg },
			ModeMsg = { fg = colors.text, bg = M.status_bg, bold = true },
			WinBar = { bg = M.ui_bg },
			WinBarNC = { bg = M.ui_bg },
			WinSeparator = { fg = M.pane_border, bg = M.ui_bg },
			DiffAdd = { fg = colors.green, bg = "#102418" },
			DiffChange = { fg = colors.yellow, bg = "#24210f" },
			DiffDelete = { fg = colors.red, bg = "#2a1014" },
			DiffText = { fg = colors.text, bg = "#3a3214", bold = true },
		}
	end,
})
vim.cmd.colorscheme("catppuccin")

return M
